[tool.poetry]
name = "tsne"
version = "0.1.0"
description = "Numba-base parallelized t-Stochastic Neighbors Embedding"
authors = ["Rémy Dubois <remydubois14@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remydubois/tsne"
keywords = []
classifiers=["Programming Language :: Python :: 3", "Topic :: Scientific/Engineering"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "1.19.5"
numba = "0.53.1"

[tool.poetry.dev-dependencies]
tqdm = "4.50.2"
scikit_learn = "0.24.1"
matplotlib = "3.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
